CREATE TABLE platform_chat_generation_receipts (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  guid BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  generation_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  mode INT NOT NULL,
  conversation_id BIGINT NOT NULL,
  user_message_id BIGINT NOT NULL,
  successful_model_count INT NOT NULL,
  daily_calls_charged INT NOT NULL,
  total_tokens BIGINT NOT NULL,
  committed_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  created_by BIGINT NULL,
  updated_at BIGINT NOT NULL,
  updated_by BIGINT NULL,
  is_deleted INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_platform_chat_generation_receipts_guid (guid),
  UNIQUE KEY uk_platform_chat_generation_receipts_owner_generation (user_id, generation_id),
  UNIQUE KEY uk_platform_chat_generation_receipts_user_message (user_message_id),
  KEY idx_platform_chat_generation_receipts_owner_active_created (user_id, is_deleted, created_at),
  KEY idx_platform_chat_generation_receipts_conversation_active (conversation_id, is_deleted),
  CONSTRAINT fk_platform_chat_generation_receipts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_platform_chat_generation_receipts_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_platform_chat_generation_receipts_user_message FOREIGN KEY (user_message_id) REFERENCES messages(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT chk_platform_chat_generation_receipts_mode CHECK (mode IN (1, 2)),
  CONSTRAINT chk_platform_chat_generation_receipts_counts CHECK (successful_model_count >= 1 AND daily_calls_charged = successful_model_count AND total_tokens >= 0),
  CONSTRAINT chk_platform_chat_generation_receipts_time CHECK (committed_at > 0 AND updated_at = created_at),
  CONSTRAINT chk_platform_chat_generation_receipts_deleted CHECK (is_deleted IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE platform_chat_generation_results (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  guid BIGINT NOT NULL,
  receipt_id BIGINT NOT NULL,
  model_index INT NOT NULL,
  model VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  status INT NOT NULL,
  assistant_message_id BIGINT NULL,
  tokens BIGINT NOT NULL DEFAULT 0,
  error_code VARCHAR(64) NULL,
  created_at BIGINT NOT NULL,
  created_by BIGINT NULL,
  updated_at BIGINT NOT NULL,
  updated_by BIGINT NULL,
  is_deleted INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_platform_chat_generation_results_guid (guid),
  UNIQUE KEY uk_platform_chat_generation_results_model (receipt_id, model),
  UNIQUE KEY uk_platform_chat_generation_results_position (receipt_id, model_index),
  UNIQUE KEY uk_platform_chat_generation_results_message (assistant_message_id),
  KEY idx_platform_chat_generation_results_receipt_active (receipt_id, is_deleted),
  CONSTRAINT fk_platform_chat_generation_results_receipt FOREIGN KEY (receipt_id) REFERENCES platform_chat_generation_receipts(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_platform_chat_generation_results_message FOREIGN KEY (assistant_message_id) REFERENCES messages(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT chk_platform_chat_generation_results_position CHECK (model_index >= 0),
  CONSTRAINT chk_platform_chat_generation_results_status CHECK (status IN (1, 2)),
  CONSTRAINT chk_platform_chat_generation_results_tokens CHECK (tokens >= 0),
  CONSTRAINT chk_platform_chat_generation_results_shape CHECK (
    (status = 1 AND assistant_message_id IS NOT NULL AND error_code IS NULL) OR
    (status = 2 AND assistant_message_id IS NULL AND tokens = 0 AND error_code IS NOT NULL)
  ),
  CONSTRAINT chk_platform_chat_generation_results_time CHECK (updated_at = created_at),
  CONSTRAINT chk_platform_chat_generation_results_deleted CHECK (is_deleted IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
