CREATE TABLE IF NOT EXISTS public_model_configs (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  guid BIGINT NOT NULL,
  model_key VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  upstream_model_id VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  display_name VARCHAR(128) NOT NULL,
  provider VARCHAR(128) NOT NULL,
  capabilities JSON NOT NULL,
  context_window BIGINT NOT NULL,
  input_price_usd_per_million_tokens DECIMAL(20,8) NULL,
  output_price_usd_per_million_tokens DECIMAL(20,8) NULL,
  status INT NOT NULL,
  inactive_reason VARCHAR(128) NULL,
  last_upstream_observed_at BIGINT NULL,
  last_upstream_check_at BIGINT NULL,
  consecutive_absences INT NOT NULL DEFAULT 0,
  revision BIGINT NOT NULL DEFAULT 1,
  ever_published INT NOT NULL DEFAULT 0,
  created_at BIGINT NOT NULL,
  created_by BIGINT NULL,
  updated_at BIGINT NOT NULL,
  updated_by BIGINT NULL,
  is_deleted INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_public_model_configs_guid (guid),
  UNIQUE KEY uk_public_model_configs_model_key (model_key),
  UNIQUE KEY uk_public_model_configs_upstream_model_id (upstream_model_id),
  KEY idx_public_model_configs_status_revision (status, is_deleted, revision),
  KEY idx_public_model_configs_provider_active (provider, is_deleted, display_name),
  CONSTRAINT chk_public_model_configs_status CHECK (status IN (1, 2, 3)),
  CONSTRAINT chk_public_model_configs_values CHECK (context_window > 0 AND consecutive_absences >= 0 AND revision > 0 AND ever_published IN (0, 1) AND is_deleted IN (0, 1)),
  CONSTRAINT chk_public_model_configs_prices CHECK ((input_price_usd_per_million_tokens IS NULL OR input_price_usd_per_million_tokens >= 0) AND (output_price_usd_per_million_tokens IS NULL OR output_price_usd_per_million_tokens >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS public_price_snapshots (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  guid BIGINT NOT NULL,
  version BIGINT NOT NULL,
  reason INT NOT NULL,
  source_revision BIGINT NOT NULL,
  content_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  restored_from_snapshot_id BIGINT NULL,
  published_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  created_by BIGINT NULL,
  updated_at BIGINT NOT NULL,
  updated_by BIGINT NULL,
  is_deleted INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_public_price_snapshots_guid (guid),
  UNIQUE KEY uk_public_price_snapshots_version (version),
  KEY idx_public_price_snapshots_version (version, is_deleted),
  KEY idx_public_price_snapshots_restore (restored_from_snapshot_id, is_deleted),
  CONSTRAINT fk_public_price_snapshots_restore FOREIGN KEY (restored_from_snapshot_id) REFERENCES public_price_snapshots(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT chk_public_price_snapshots_reason CHECK (reason IN (1, 2, 3)),
  CONSTRAINT chk_public_price_snapshots_values CHECK (version > 0 AND source_revision > 0 AND published_at > 0 AND is_deleted IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS public_price_snapshot_items (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  guid BIGINT NOT NULL,
  snapshot_id BIGINT NOT NULL,
  model_config_id BIGINT NOT NULL,
  model_key VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  upstream_model_id VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  display_name VARCHAR(128) NOT NULL,
  provider VARCHAR(128) NOT NULL,
  capabilities JSON NOT NULL,
  context_window BIGINT NOT NULL,
  input_price_usd_per_million_tokens DECIMAL(20,8) NOT NULL,
  output_price_usd_per_million_tokens DECIMAL(20,8) NOT NULL,
  upstream_checked_at BIGINT NULL,
  created_at BIGINT NOT NULL,
  created_by BIGINT NULL,
  updated_at BIGINT NOT NULL,
  updated_by BIGINT NULL,
  is_deleted INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_public_price_snapshot_items_guid (guid),
  UNIQUE KEY uk_public_price_snapshot_items_snapshot_model (snapshot_id, model_config_id),
  UNIQUE KEY uk_public_price_snapshot_items_snapshot_key (snapshot_id, model_key),
  KEY idx_public_price_snapshot_items_model (model_config_id, is_deleted),
  CONSTRAINT fk_public_price_snapshot_items_snapshot FOREIGN KEY (snapshot_id) REFERENCES public_price_snapshots(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_public_price_snapshot_items_model FOREIGN KEY (model_config_id) REFERENCES public_model_configs(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT chk_public_price_snapshot_items_values CHECK (context_window > 0 AND input_price_usd_per_million_tokens >= 0 AND output_price_usd_per_million_tokens >= 0 AND is_deleted IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS public_content_drafts (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  guid BIGINT NOT NULL,
  document_kind INT NOT NULL,
  payload JSON NOT NULL,
  revision BIGINT NOT NULL DEFAULT 1,
  review_state INT NOT NULL DEFAULT 1,
  created_at BIGINT NOT NULL,
  created_by BIGINT NULL,
  updated_at BIGINT NOT NULL,
  updated_by BIGINT NULL,
  is_deleted INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_public_content_drafts_guid (guid),
  UNIQUE KEY uk_public_content_drafts_document_active (document_kind, is_deleted),
  KEY idx_public_content_drafts_document_revision (document_kind, revision, is_deleted),
  CONSTRAINT chk_public_content_drafts_kind CHECK (document_kind IN (1, 2, 3, 4, 5)),
  CONSTRAINT chk_public_content_drafts_review CHECK (review_state IN (1, 2)),
  CONSTRAINT chk_public_content_drafts_values CHECK (revision > 0 AND is_deleted IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS public_content_releases (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  guid BIGINT NOT NULL,
  document_kind INT NOT NULL,
  version BIGINT NOT NULL,
  source_revision BIGINT NOT NULL,
  payload JSON NOT NULL,
  content_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  restored_from_release_id BIGINT NULL,
  published_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  created_by BIGINT NULL,
  updated_at BIGINT NOT NULL,
  updated_by BIGINT NULL,
  is_deleted INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_public_content_releases_guid (guid),
  UNIQUE KEY uk_public_content_releases_document_version (document_kind, version),
  KEY idx_public_content_releases_document_version (document_kind, version, is_deleted),
  KEY idx_public_content_releases_restore (restored_from_release_id, is_deleted),
  CONSTRAINT fk_public_content_releases_restore FOREIGN KEY (restored_from_release_id) REFERENCES public_content_releases(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT chk_public_content_releases_kind CHECK (document_kind IN (1, 2, 3, 4, 5)),
  CONSTRAINT chk_public_content_releases_values CHECK (version > 0 AND source_revision > 0 AND published_at > 0 AND is_deleted IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS public_publication_state (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  guid BIGINT NOT NULL,
  state_key VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  price_snapshot_id BIGINT NULL,
  content_release_id BIGINT NULL,
  price_visibility INT NOT NULL,
  revision BIGINT NOT NULL DEFAULT 1,
  created_at BIGINT NOT NULL,
  created_by BIGINT NULL,
  updated_at BIGINT NOT NULL,
  updated_by BIGINT NULL,
  is_deleted INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_public_publication_state_guid (guid),
  UNIQUE KEY uk_public_publication_state_key (state_key),
  KEY idx_public_publication_state_revision (revision, is_deleted),
  CONSTRAINT fk_public_publication_state_price FOREIGN KEY (price_snapshot_id) REFERENCES public_price_snapshots(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_public_publication_state_content FOREIGN KEY (content_release_id) REFERENCES public_content_releases(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT chk_public_publication_state_visibility CHECK (price_visibility IN (1, 2)),
  CONSTRAINT chk_public_publication_state_values CHECK (revision > 0 AND is_deleted IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS upstream_model_observations (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  guid BIGINT NOT NULL,
  upstream_model_id VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  provider VARCHAR(128) NOT NULL,
  input_price_usd_per_million_tokens DECIMAL(20,8) NULL,
  output_price_usd_per_million_tokens DECIMAL(20,8) NULL,
  catalog_complete INT NOT NULL,
  catalog_fresh INT NOT NULL,
  observed_at BIGINT NOT NULL,
  response_summary_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  created_at BIGINT NOT NULL,
  created_by BIGINT NULL,
  updated_at BIGINT NOT NULL,
  updated_by BIGINT NULL,
  is_deleted INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_upstream_model_observations_guid (guid),
  UNIQUE KEY uk_upstream_model_observations_identity (upstream_model_id, observed_at),
  KEY idx_upstream_model_observations_observed_at (observed_at, is_deleted),
  KEY idx_upstream_model_observations_model_observed (upstream_model_id, is_deleted, observed_at),
  CONSTRAINT chk_upstream_model_observations_catalog CHECK (catalog_complete IN (0, 1) AND catalog_fresh IN (0, 1) AND is_deleted IN (0, 1)),
  CONSTRAINT chk_upstream_model_observations_prices CHECK ((input_price_usd_per_million_tokens IS NULL OR input_price_usd_per_million_tokens >= 0) AND (output_price_usd_per_million_tokens IS NULL OR output_price_usd_per_million_tokens >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS root_alerts (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  guid BIGINT NOT NULL,
  model_config_id BIGINT NULL,
  model_key VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  alert_type INT NOT NULL,
  state INT NOT NULL,
  fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  payload JSON NOT NULL,
  occurrence_count INT NOT NULL DEFAULT 1,
  first_observed_at BIGINT NOT NULL,
  last_observed_at BIGINT NOT NULL,
  resolved_at BIGINT NULL,
  created_at BIGINT NOT NULL,
  created_by BIGINT NULL,
  updated_at BIGINT NOT NULL,
  updated_by BIGINT NULL,
  is_deleted INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_root_alerts_guid (guid),
  UNIQUE KEY uk_root_alerts_fingerprint (fingerprint),
  KEY idx_root_alerts_active (state, is_deleted, updated_at),
  KEY idx_root_alerts_model_active (model_config_id, state, is_deleted),
  CONSTRAINT fk_root_alerts_model FOREIGN KEY (model_config_id) REFERENCES public_model_configs(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT chk_root_alerts_type CHECK (alert_type IN (1, 2, 3, 4, 5, 6, 7)),
  CONSTRAINT chk_root_alerts_state CHECK (state IN (1, 2)),
  CONSTRAINT chk_root_alerts_values CHECK (occurrence_count > 0 AND first_observed_at > 0 AND last_observed_at >= first_observed_at AND is_deleted IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS root_alert_receipts (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  guid BIGINT NOT NULL,
  alert_id BIGINT NOT NULL,
  root_user_id BIGINT NOT NULL,
  read_at BIGINT NULL,
  acknowledged_at BIGINT NULL,
  created_at BIGINT NOT NULL,
  created_by BIGINT NULL,
  updated_at BIGINT NOT NULL,
  updated_by BIGINT NULL,
  is_deleted INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_root_alert_receipts_guid (guid),
  UNIQUE KEY uk_root_alert_receipts_alert_root (alert_id, root_user_id),
  KEY idx_root_alert_receipts_root_unread (root_user_id, is_deleted, read_at),
  CONSTRAINT fk_root_alert_receipts_alert FOREIGN KEY (alert_id) REFERENCES root_alerts(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_root_alert_receipts_root FOREIGN KEY (root_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT chk_root_alert_receipts_deleted CHECK (is_deleted IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS public_render_jobs (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  guid BIGINT NOT NULL,
  price_snapshot_id BIGINT NOT NULL,
  content_release_id BIGINT NOT NULL,
  state INT NOT NULL,
  lease_owner_hmac CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  lease_expires_at BIGINT NULL,
  attempt_count INT NOT NULL DEFAULT 0,
  last_failure VARCHAR(1024) NULL,
  completed_at BIGINT NULL,
  created_at BIGINT NOT NULL,
  created_by BIGINT NULL,
  updated_at BIGINT NOT NULL,
  updated_by BIGINT NULL,
  is_deleted INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_public_render_jobs_guid (guid),
  UNIQUE KEY uk_public_render_jobs_release_pair (price_snapshot_id, content_release_id),
  KEY idx_public_render_jobs_lease (state, is_deleted, lease_expires_at),
  CONSTRAINT fk_public_render_jobs_price FOREIGN KEY (price_snapshot_id) REFERENCES public_price_snapshots(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_public_render_jobs_content FOREIGN KEY (content_release_id) REFERENCES public_content_releases(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT chk_public_render_jobs_state CHECK (state IN (1, 2, 3, 4)),
  CONSTRAINT chk_public_render_jobs_values CHECK (attempt_count >= 0 AND is_deleted IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
